
kubeclient:
  namespace: kube-system
  qps: 500
  burst: 1000
  clusters:
    main:
      name: main
      # config is the content of kubeconfig in base64
      #  if config is empty, use kubeconfig in $HOME/.kube/config in-cluster config
      config: ""
    ai-dev:
      name: ai-dev
      config: ""
