
kubeclient:
  qps: 500
  burst: 1000
  cluster:
    name: default
    # config is the content of kubeconfig in base64
    #  if config is empty, use kubeconfig in $HOME/.kube/config in-cluster config
    config: ""